### ISSUE TITLE
Al corregir, soportar política "estricta" para la fecha límite

### ISSUE THREAD

**Issue by faloi** [faloi/yanapiri#10]
En caso que se elija esa opción, el PR debería crearse con el último commit anterior a la fecha límite. 

Quizás agregando un mensaje al estudiante que le indique que tales commits no fueron tenidos en cuenta.

**Comment by faloi** [comment]
@npasserini, ¿cómo la ves?

**Comment by npasserini** [comment]
Suena bien. Igualmente, como te decía antes, no me parece un feature
crucial.

En cambio, a lo mejor sería piola ofrecer comandos de más bajo nivel, para
que cada uno pueda armarse su circuito.
Por ejemplo, el corregir hoy entiendo que corrije el nombre, genera el PR.
¿Podría yo ejecutar esas cosas por separado?
Eso evitaría que alguien commitee los proyectos renombrados si le conviene
más de esa manera.

A la larga, podría ejecutar cualquier comando git contra los repos, eso me
lo imagino fácil.
Y bueno, lo de crear PRs no sé qué tan flexible puede ser.

Perdón, estoy un poco apretado ahora y no tengo mucho más tiempo que para
tirar una idea fumada así. Espero de acá a no mucho poder sentarme y tirar
un PR en lugar de sólo molestarte.
