### ISSUE TITLE
Hacer un "fork" individual de un assignment grupal

### ISSUE THREAD

**Issue by faloi** [faloi/yanapiri#40]
Util para armar una defensa individual de un TP grupal, que requiera agregarle funcionalidades al código grupal.

Debería:
1. Crear un repo privado nuevo bajo la organización, con sufijo `-defensa-<usuario>`, para cada miembro del team.
1. Agregar al usuario como _collaborator_, con permiso de **Write**.
1. Pushear el código del repo original al nuevo.

**Comment by faloi** [comment]
@npasserini @PalumboN @fdodino tenemos una defensa la semana que viene y voy a estar laburando en esto... ¿alguna vez tuvieron una necesidad parecida? ¿cómo resolvieron?

**Comment by fdodino** [comment]
no exactamente, justo la otra vez estábamos pensando en tener una kata parte presencial y parte en la casa, y ahí habría que decidir una de estas dos opciones:

- lo hacemos grupal y después cada uno trabaja un punto individual
- lo hacemos individual y después el otro forkea el repo y sigue un punto que faltaría

**Comment by PalumboN** [comment]
Yo nunca estuve en esta situación. Pero eso que describís es lo que hace Github Classroom. No se podría crea un assignment individual con el código del grupal como base?

**Comment by faloi** [comment]
@fdodino: pensé en resolverlo pidiendole a lxs estudiantes que forkeen y ya, pero eso implicaría hacer públicos todos los repos (para las entregas usamos repo privado).

@PalumboN: sí, pero habría que crear tantos assignments como grupos haya. Y GH Classroom no tiene api, sería sí o sí a manopla.

**Comment by faloi** [comment]
Al final lo vamos a hacer a manopla: crear un assignment nuevo y pedirle a cada estudiante que copie el código de la entrega anterior. No es lo mejor, pero estamos corriendo con los tiempos y no hay tiempo ahora para desarrollar esto.

**Comment by npasserini** [comment]
Nunca hicimos forks individuales, pero asumo que de última se puede hacer a
mano forkeando en github sin necesidad del copiar el código.
