### ISSUE TITLE
Compatibilidad con GitHub Template

### ISSUE THREAD

**Issue by PalumboN** [faloi/yanapiri#45]
Ahora GitHub permite la opción de que un repo pueda ser usado como _template_. Esto permite crear un nuevo repo a partir del template, pero en vez de tener toda la historia **crea un solo commit inicial con tooodo el código actual**.

Nosotros usamos esto con GHClassroom porque nos resuelve un problema, que tuvimos varias veces, de que se quedaba colgado la importación de código inicial.

Un problema con esto, es que ahora **no existe un mismo commit base para todos** los repositorios de una actividad, entonces no podemos usar Yanapiri :(

Estaría bueno poder decir en el comando "corregir" si los repos fueron creados a partir de un template para **que tome como base el primer commit** (quizás pueda ser un default de si no te paso un commit base ?)

**Comment by faloi** [comment]
Existe la posiblidad de decirle que tome como base el primer commit, lo desarrollé para una situación parecida.

En vez de poner el SHA del commit tenés que poner `index:1` (o 2, 7, el que quieras). Probalo y si funca cerrá la issue. También podés mejorar el README contando más de cómo usar yanapiri. :smiley:

**Comment by PalumboN** [comment]
Buenísimo! Ahí funcó!!! Qué maravilla. Y vi que ya estaba documentado, simplemente no volví a leer el readme actualizado.
Muchas gracias señor!
